baseURL = 'https://mranand.com/'
languageCode = 'en-us'
title = 'Mr. Ånand'
theme = [ 'PaperMod', 'hugo-shortcodes', 'hugo-embed-pdf-shortcode' ]
paginate = 5


enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "G-V0FWJ50Z7L"

[minify]
disableXML = false
minifyOutput = true

[params]
env = "production"
ShowShareButtons = true
ShowCodeCopyButtons = true
ShowFullTextinRSS = true
# comments = true
defaultTheme = "dark"
description = "Tech blogger from India. Open-Source and Self-Learning. Love to create different types of content. Student | Content Creator | Explorer and Learner"
keywords = [ "Blogger", "India", "Selflearning", "Blog", "Portfolio", "PaperMod", "GitHub", "open source", "JavaScript", "Astrodevil", "Content", "Developers", "100Daysofcode", "codesastro", "Webdevelopment", "Student", "Web3", "Programming", "Coding", "Technicalwriter", "Creator", "mranand", "Mr. Ånand", "Amitesh", "Amitesh Anand", "Programming", "Tutorial", "Books", "Project", "Hugo" ]
enableEmoji = true


[outputs]
home = [ "HTML", "RSS", "JSON" ]


[[menu.main]]
identifier = "blog"
name = "Blogs"
url = "/blogs/"
weight = 10

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 30

#[[menu.main]]
#identifier = "categories"
#name = "Categories"
#url = "/categories/"
#weight = 30
                        # categories and Series features will be enabled if required
#[[menu.main]]
#identifier = "series"
#name = "Series"
#url = "/series/"
#weight = 30

[[menu.main]]
identifier = "Featured"
name = "Featured"
url = "/featured/"
weight = 40

[[menu.main]]
identifier = "Gallery"
name = "Gallery"
url = "/gallery/"
weight = 50

[[menu.main]]
identifier = "E-Book"
name = "E-Books"
url = "/E-books/"
weight = 60

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 70

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 80

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 90




[params.profileMode]
enabled = true
title = "Mr. Ånand"
subtitle = "Student | Content Creator | Explorer and Learner"
subtitle1 = "CSE Undergraduate👨🏼‍💻 | Blogger✍🏼"
imageUrl = "https://cdn.bio.link/uploads/profile_pictures/2021-12-17/rIgWZLgFZMi84ZKzAZ2Rw3K2PbIJ5PJk.png"
imageTitle = "Mr. Ånand"
imageWidth = 120
imageHeight = 120



[[params.profileMode.buttons]]  
  name = "Works"
  url = "https://bio.link/astrodevil"
[[params.profileMode.buttons]]
  name = "Newsletter"
  url = "https://zerooctave.substack.com/"
[[params.profileMode.buttons]]
  name = "Resume"
  url = "https://drive.google.com/file/d/1zC81LO5XOmLDd7KhCJlsM96w1J4HaEcw/view?usp=sharing"


[params.HugoShortcodes.Gumroad]
    Host = 'https://astrodevil.gumroad.com'
#    Affiliate = '123456789'

[analytics.google]
SiteVerificationTag = "XYZabc"

[analytics.bing]
SiteVerificationTag = "F5A3921E8BDE49E6E1D5718A318B8C2B"

[analytics.yandex]
SiteVerificationTag = "XYZabc"


[[params.socialIcons]]
name = "twitter"
url = "https://mobile.twitter.com/astrodevil_"

[[params.socialIcons]]
name = "medium"
url = "https://astrodevil.medium.com/"

[[params.socialIcons]]
name = "instagram"
url = "https://www.instagram.com/codes.astro/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/Astrodevil"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/amitesh1208/"

[[params.socialIcons]]
name = "RSS"
url = "/index.xml"

[taxonomies]
   series = "series"
   tags = "tags"
   category = "categories"